### ISSUE TITLE
Błąd przy adresach z polskimi znakami

### ISSUE THREAD

**Issue by ShinJii89** [mariusz-zajac/fakturownia#4]
Cześć,
Nie wiedzieć czemu fakturownia.pl zezwala na polskie znaki w nazwie domeny np. testół.fakturownia.pl - zauważyłem to u jednego z klientów u którego nie chce się wygenerować faktura od 10 dni i zauważyłem, że powodem są polskie znaki w adresie - dasz radę wydać szybko jakąś łatkę? 
Najlepiej do 28.05 bo później już będą ludzie się rozliczać za maj, a faktura dalej nie wystawiona...

`Fatal error: Uncaught Abb\Fakturownia\Exception\RequestErrorException: Could not resolve host: PolskieZnakiół.fakturownia.pl in /home/acdm/domains/domena.pl/public_html/subdomains/test/includes/libs/fakturownia/vendor/abb/fakturownia/src/FakturowniaRestClient.php:104 Stack trace: #0 /home/acdm/domains/domena.pl/public_html/subdomains/test/includes/libs/fakturownia/vendor/abb/fakturownia/src/FakturowniaRestClient.php(49): Abb\Fakturownia\FakturowniaRestClient->request('POST', 'https://PolskieZnakiół...', Array) #1 /home/acdm/domains/domena.pl/public_html/subdomains/test/includes/libs/fakturownia/vendor/abb/fakturownia/src/Fakturownia.php(116): Abb\Fakturownia\FakturowniaRestClient->post('https://PolskieZnakiół...', Array) #2 /home/acdm/domains/domena.pl/public_html/subdomains/test/includes/functions.php(927): Abb\Fakturownia\Fakturownia->createInvoice(Array) #3 /home/acdm/domains/domena.pl/public_html/subdomains/test/crons/faktury-paragony.cron.php(33): invoicegenerate('XKVWS8QX4P21051...', Array, Array, Array, '9.99', Array, in /home/acdm/domains/domena.pl/public_html/subdomains/test/includes/libs/fakturownia/vendor/abb/fakturownia/src/FakturowniaRestClient.php on line 104`

**Comment by ShinJii89** [comment]
Dobra, to jednak nie wina tej wtyczki, a wina nie zainstalowanych pakietów na serwerze linuxa - LIBIDN oraz LIBIDN-DEVEL - po instalacji i przekompilowaniu CURLa wszystko śmiga :))) - taka ciekawostka.

**Comment by ShinJii89** [comment]
Jednak jest problem - po konwersji URLa przez CURL wyskakuje błąd z fakturowni w stylu:

`array ( 'code' => 'error', 'message' => 'Musisz być zalogowany, aby mieć dostęp do strony https://xn--testznak-23a40f.fakturownia.pl/invoices.json', )`
Teraz nie wiem czy to wina stricte fakturownia.pl czy Twojej wtyczki :)

Przykładowa domena: testznakół.fakturownia.pl
@mariusz-zajac 

EDIT: Wydaje mi się mimo wszystko, że to wina fakturownia.pl - napisałem do nich również przy okazji :D dam znać jak odpiszą.

**Comment by ShinJii89** [comment]
Eeee... dobra...to jednak klientka jakiś dziwny token wprowadziła, w fakturowni on nie istnieje... co za luzdie... sorki za kłopot ;)
